research = {
    housing1: {
      age: 0,
      fullName: "Housing I",
      info: "Unlocks Dolmen",
      cost: 2500,
      unlocked:false,
      requiredResearch: [ ],
    },
    plantGathering1: {
      age: 0,
      fullName: "Plant Gathering I",
      info: "Unlocks gatheringCamp.",
      cost: 2500,
      unlocked:false,
      requiredResearch: [ ],
    },
    tools1: {
      age: 0,
      fullName: "Tools I",
      info: "Unlocks the ability to produce primitive tools using the flintKnapper and woodWorker.",
      cost: 2500,
      unlocked:false,
      requiredResearch: [ ],
    },
    hunting: {
      age: 0,
      fullName: "Hunting I",
      info: "Unlocks huntingCamp.",
      cost: 2500,
      unlocked:false,
      requiredResearch: [ tools1 ],
    },
    fire: {
      age: 1,
      fullName: "Invention of fire",
      info: "Understand and harness the power of fire.",
      cost: 25000,
      unlocked:false,
      requiredResearch: [ tools1 ],
    },
    plantGathering2: {
      age: 1,
      fullName: "Plant Gathering II",
      info: "The understanding of roots unlocks the gathering of rootVegetables.",
      cost: 25000,
      unlocked:false,
      requiredResearch: [ plantGathering1 ],
    },
    housing2: {
      age: 1,
      fullName: "Housing II",
      info: "Unlocks Hut",
      cost: 25000,
      unlocked:false,
      requiredResearch: [ fire, housing1 ],
      },
}